services: mongodb
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails30.gemfile 
  - gemfiles/rails31.gemfile 
  - gemfiles/rails32.gemfile 
  - gemfiles/rails4.gemfile 
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/rails32.gemfile 
    - rvm: 1.9.2
      gemfile: gemfiles/rails4.gemfile 
